# Introducción a las ciencias de la computación *y programación en Python*

*Banco de Guatemala*  
*PES 2025-2026*  
*Programación I*  
*Septiembre de 2025*  

## Abstract

> "*I do not fear computers. I fear lack of them.*" **Isaac Asimov**

- Paquete de computación científica NumPy

    - Introducción
    
    - Conceptos básicos de utilización
    
    - Ejercicios

# NumPy

- Paquete de Python para **computación científica** de **alto desempeño** sobre vectores, matrices y estructuras de mayores dimensiones (tensores).

- Implementado en C y Fortran, por lo que cuando se **vectorizan** las oepraciones, el desempeño es muy bueno.

- Ofrece una estructura de datos `ndarray` para procesar de forma **eficiente** datos homogéneos.

- Capacidades de algebra lineal, transformada de Fourier y generación de números aleatorios.

## Pero, ¿y las listas de Python?

- Las listas son muy generales, pueden contener cualquier tipo de objeto.

    - Implementan tipos dinámicos.
    
    - No permiten operaciones matemáticas como la *multiplicación matricial* o *producto punto*.
    
- Los vectores de NumPy son de tipado estático y homogéneo. El tipo del arreglo se determina cuando se crea el vector.

    - Son eficientes en memoria.
    
    - Es posible implementar **funciones universales** (ufuncs). 
    
    - El tipado estático permite implementar operaciones matemáticas de forma eficiente a través de C y Fortran.
    

### Comparación entre lenguajes de programación

![julia-benchmarks.svg](figs/numpy/julia-benchmarks.svg)

[5 Razones para aprender NumPy](https://insights.dice.com/2016/09/01/5-reasons-know-numpy/): 

    It's fast
    It works very well with SciPy and other Libraries
    It lets you do matrix arithmetic
    It has lots of built-in functions
    It has universal functions


## Importando NumPy

In [155]:
import numpy as np

- Revisamos la versión de NumPy (importante al ver la documentación)

In [156]:
np.__version__

'2.3.3'

### Obteniendo ayuda

In [157]:
# Obtiene una ventana de ayuda
np.ndarray?

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [158]:
# Función help para una función
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

***
## La clase `ndarray`

- La clase básica de NumPy se llama `ndarray` (alias `array`). Sus atributos más importantes son: 

    - `ndarray.ndim` : número de dimensiones del arreglo.

    - `ndarray.shape` : dimensiones del arreglo. Esta es una **tupla de enteros** que indica el tamaño de la matriz en cada dimensión. Para una matriz con $n$ filas y $m$ columnas, la forma será $(n, m)$. La longitud de la tupla de forma es, por lo tanto, el número de ejes, `ndim`.

    - `darray.size` : el número total de elementos del arreglo. Es igual al producto de los elementos de la tupla `shape`.

    - `ndarray.dtype` : un **objeto** que describe el **tipo** de los elementos en el arreglo. Es posible crear y especificar `dtypes` propios.
        - Adicionalmente, NumPy provee algunos tipos propios muy utilizados: `numpy.int32`, `numpy.int16`, and `numpy.float64`.

    - `ndarray.itemsize` : el tamaño en bytes de cada elemento en el arreglo. Por ejemplo, un arreglo de tipo `float64` tiene tamaño en bytes de $8 (=64/8)$. Equivalente a `ndarray.dtype.itemsize`.

    - `ndarray.data` : el búfer que contiene los elementos del arreglo. Aunque normalmente, no accedemos al atributo directamente, ya que hacemos uso de los elementos con *slicing*.



In [159]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [160]:
a.shape

(3, 5)

In [161]:
a.ndim

2

In [162]:
a.dtype

dtype('int64')

In [163]:
a.dtype.name

'int64'

In [164]:
a.itemsize

8

In [165]:
a.size

15

In [166]:
type(a)

numpy.ndarray

***
# Creando arreglos N-dimensionales de NumPy

- Hay varias formas de inicializar nuevas matrices numpy, por ejemplo desde

    - Una lista de Python o tuplas.
    
    - Utilizando funciones dedicadas a **generar** arreglos de NumPy.

      - Es común inicializar vectores de ceros o con valores aleatorios.
    
    - Leer información de archivos. 

In [167]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [168]:
a.dtype

dtype('int64')

In [169]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [170]:
b.dtype

dtype('float64')

### Error frecuente

Crear el arreglo con varios argumentos en vez de proveer una sola lista o secuencia como argumento

In [171]:
# Error frecuente
a = np.array(1,2,3,4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

## A partir de listas o tuplas 
`ndarray` transforma secuencias de secuencias en matrices bidimensionales, secuencias de secuencias de secuencias en matrices tridimensionales, etc.

In [ ]:
b = np.array([[1.5,2,3], [4,5,6]])
b

El tipo de matriz también se puede especificar explícitamente en el momento de la creación:

In [ ]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

## Funciones de generación de arreglos

In [ ]:
np.arange(10, 30, 5)

In [ ]:
# A diferencia de range
np.arange(0, 2, 0.3)

#### Evaluación de funciones

Notar que la evaluación de funciones es "vectorizada", es decir, sobre todos los elementos del arreglo a la vez. 

- ¡Evitamos los ciclos `for` de Python porque son más lentos!

In [ ]:
x = np.linspace(0, 2*np.pi, 20)
x

In [ ]:
y = np.sin(x)
y 

##  Variables aleatorias

In [ ]:
b = np.random.random((5, 5))
b

## Unos, ceros

In [ ]:
np.zeros([10, 10])

In [ ]:
np.ones([5, 5])

In [ ]:
# Copiando la forma de x
np.ones_like(x)

In [ ]:
np.identity(5)

## Desde archivos

In [ ]:
data = np.loadtxt("data/data.csv", delimiter=',', skiprows=1)
data

array([[1.00000000e+00, 3.44899870e-01],
       [2.00000000e+00, 9.31072695e-01],
       [3.00000000e+00, 6.25704035e-01],
       [4.00000000e+00, 8.41599361e-01],
       [5.00000000e+00, 8.87112967e-01],
       [6.00000000e+00, 5.58222238e-01],
       [7.00000000e+00, 3.05687170e-02],
       [8.00000000e+00, 7.21006651e-01],
       [9.00000000e+00, 2.15081930e-02],
       [1.00000000e+01, 4.89341526e-01],
       [1.10000000e+01, 3.23284084e-01],
       [1.20000000e+01, 1.86885658e-01],
       [1.30000000e+01, 4.64906445e-01],
       [1.40000000e+01, 5.60553301e-01],
       [1.50000000e+01, 3.83349378e-01],
       [1.60000000e+01, 4.76682101e-01],
       [1.70000000e+01, 9.40387708e-01],
       [1.80000000e+01, 4.03836182e-01],
       [1.90000000e+01, 8.30264821e-01],
       [2.00000000e+01, 2.50129241e-01],
       [2.10000000e+01, 5.85427477e-01],
       [2.20000000e+01, 9.33801603e-01],
       [2.30000000e+01, 6.32389807e-01],
       [2.40000000e+01, 1.85051348e-01],
       [2.500000

***
# Impresión de arreglos

Cuando imprimes una matriz, NumPy la muestra de forma similar a las listas anidadas, pero con el siguiente diseño:

- el último eje se imprime de izquierda a derecha,

- el penúltimo se imprime de arriba a abajo,

- el resto también se imprime de arriba a abajo, con cada corte separado del siguiente por una línea vacía.

Las matrices unidimensionales se imprimen como filas, bidimensionales como matrices y tridimensionales como listas de matrices.

In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
c = np.arange(24).reshape(2,3,4) 
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# Si es muy grande, se suprime parte de la salida
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [ ]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


***
# Operaciones básicas

Las operaciones básicas son aplicadas elemento a elemento (*elementwise*). Se crea un nuevo arreglo lleno con el resultado

In [ ]:
a = np.array( [20,30,40,50] )
b = np.arange(4)
a, b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [ ]:
c = a - b
c

array([20, 29, 38, 47])

`*` opera en sentido elemento a elemento sobre los arreglos.

In [ ]:
# Constante por arreglo
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [ ]:
a*b # da una multiplicación de elemento a elemento.

In [ ]:
# Arreglos lógicos
a < 35

array([ True,  True, False, False])

In [ ]:
a[a<35] # filtro solo los elementos menores a 35

array([20, 30])

La multiplicación matricial puede hacerse utilizando `@` o el método `dot`

In [ ]:
A = np.array( [[1, 1], [0, 1]] )
B = np.array( [[2, 0], [3, 4]] )

In [ ]:
A * B

array([[2, 0],
       [0, 4]])

In [ ]:
A @ B # Producto matricial

array([[5, 4],
       [3, 4]])

In [ ]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [ ]:
np.matmul(A, B)

array([[5, 4],
       [3, 4]])

In [ ]:
b = np.random.random((2,3))
b

array([[0.39919227, 0.0891435 , 0.42059964],
       [0.34230663, 0.29172237, 0.86746569]])

Operadores `+=` y `*=` son válidos para modificar arreglos existentes.

In [ ]:
a = np.ones((2,3), dtype=int)
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [ ]:
b = np.random.random((2,3))
b +=a 
b

array([[3.84304441, 3.73767462, 3.2326585 ],
       [3.17264283, 3.53573384, 3.99534147]])

## Métodos útiles

In [ ]:
a = np.random.random((2, 3))
a

array([[0.59025309, 0.3126641 , 0.22685117],
       [0.37910505, 0.56352708, 0.40487034]])

In [ ]:
a.sum() # equivalente a np.sum(a)

np.float64(2.4772708326446735)

In [ ]:
a.min()

np.float64(0.2268511703510553)

In [ ]:
a.max()

np.float64(0.5902530860227594)

Por defecto operan sobre el arreglo como si fueran una lista de números. Es posible especificar el eje sobre el cuál se desea aplicar la operación con el parámetro `axis`

In [ ]:
a=np.arange(15).reshape(3,5)
a, a.sum(axis=0), a.sum(axis=1)

# Para corregir y que se vea como un vertor fila
a.sum(axis=0)[np.newaxis,:],a.sum(axis=1)[:,np.newaxis]

(array([[15, 18, 21, 24, 27]]),
 array([[10],
        [35],
        [60]]))

In [ ]:
b = np.arange(30).reshape(2,3,5)
b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
b.sum() # suma a lo largo de todas las dimensiones

np.int64(435)

In [ ]:
# Suma de las columnas 
b.sum(axis=0)   

array([[15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43]])

In [ ]:
# Mínimo de cada fila
b.min(axis=1)

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [ ]:
b.min(axis=2)

array([[ 0,  5, 10],
       [15, 20, 25]])

In [ ]:
# Suma acumulada en las columnas 
b.cumsum(axis=1)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  7,  9, 11, 13],
        [15, 18, 21, 24, 27]],

       [[15, 16, 17, 18, 19],
        [35, 37, 39, 41, 43],
        [60, 63, 66, 69, 72]]])

***
## Funciones universales (*ufuncs*)

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
np.exp(a)

In [ ]:
np.sqrt(a)

Podemos definir funciones de usuario que sean universales: $$ f(x) = 2x + e^x - \sqrt{x} $$

In [ ]:
### opera sobre todos los elementos del array
def f(x):
    return 2*x + np.exp(x) - np.sqrt(x)

In [ ]:
f(a)

array([ 1.        ,  3.71828183,  9.97484254, 24.35348612, 60.59815003])

***
## Indexing, Slicing and Iterating

Los arreglos unidimensionales se pueden indexar, dividir e iterar, al igual que las listas y otras secuencias de Python.

In [ ]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
np.shape(a) # Número de elementos por cada dimensión-
a.size ## determina número de elementos.

10

In [ ]:
a[2]

np.int64(8)

In [ ]:
a[2:5]

array([ 8, 27, 64])

In [ ]:
# Asignación múltiple
a[0:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [ ]:
for i in range(0,6,2):
    a[i]=-1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [ ]:
def f1(x,y):
    return 10*x + y

In [ ]:
b = np.fromfunction(f1, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [ ]:
b[2, 3]

np.int64(23)

In [ ]:
b[0:3, 1]

array([ 1, 11, 21])

In [ ]:
b[:, 1]

Cuando se proporcionan menos índices que el número de ejes, los índices faltantes se consideran segmentos completos `:`

In [ ]:
# Ultima fila, todas las columnas
b[-1]

array([40, 41, 42, 43])

In [ ]:
np.ones((4,3,2,1))

In [ ]:
def f(x,y,z):
    return 10*x + y+2*z

c = np.fromfunction(f, (5,4,3), dtype=int)
c

array([[[ 0,  2,  4],
        [ 1,  3,  5],
        [ 2,  4,  6],
        [ 3,  5,  7]],

       [[10, 12, 14],
        [11, 13, 15],
        [12, 14, 16],
        [13, 15, 17]],

       [[20, 22, 24],
        [21, 23, 25],
        [22, 24, 26],
        [23, 25, 27]],

       [[30, 32, 34],
        [31, 33, 35],
        [32, 34, 36],
        [33, 35, 37]],

       [[40, 42, 44],
        [41, 43, 45],
        [42, 44, 46],
        [43, 45, 47]]])

In [ ]:
c[:,2,1]

array([ 4, 14, 24, 34, 44])

La iteración sobre arreglos multidimensionales se realiza con respecto al primer eje

In [ ]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [ ]:
for row in c:
    print(row)

[[0 2 4]
 [1 3 5]
 [2 4 6]
 [3 5 7]]
[[10 12 14]
 [11 13 15]
 [12 14 16]
 [13 15 17]]
[[20 22 24]
 [21 23 25]
 [22 24 26]
 [23 25 27]]
[[30 32 34]
 [31 33 35]
 [32 34 36]
 [33 35 37]]
[[40 42 44]
 [41 43 45]
 [42 44 46]
 [43 45 47]]


Sin embargo, si se desea realizar una operación en cada elemento de la matriz, se puede usar el atributo `flat` que es un iterador sobre todos los elementos de la matriz:

In [ ]:
for element in c.flat:
    print(element)

0
2
4
1
3
5
2
4
6
3
5
7
10
12
14
11
13
15
12
14
16
13
15
17
20
22
24
21
23
25
22
24
26
23
25
27
30
32
34
31
33
35
32
34
36
33
35
37
40
42
44
41
43
45
42
44
46
43
45
47


In [ ]:
c.flatten()

array([ 0,  2,  4,  1,  3,  5,  2,  4,  6,  3,  5,  7, 10, 12, 14, 11, 13,
       15, 12, 14, 16, 13, 15, 17, 20, 22, 24, 21, 23, 25, 22, 24, 26, 23,
       25, 27, 30, 32, 34, 31, 33, 35, 32, 34, 36, 33, 35, 37, 40, 42, 44,
       41, 43, 45, 42, 44, 46, 43, 45, 47])

***
## Manipulación del `shape` (forma) del arreglo

Una matriz tiene una forma dada por el número de elementos a lo largo de cada eje:

In [ ]:
a = np.floor ( 10 * np.random.random (( 3 , 4 )))
a

array([[1., 7., 8., 8.],
       [2., 9., 5., 1.],
       [7., 6., 6., 3.]])

In [ ]:
a.shape

La forma de una matriz se puede cambiar con varios comandos. Tenga en cuenta que los siguientes tres comandos devuelven una matriz modificada, pero **no cambian la matriz original**:

In [ ]:
a.ravel()  # returns the array, flattened

array([1., 7., 8., 8., 2., 9., 5., 1., 7., 6., 6., 3.])

In [ ]:
a.flatten()

array([1., 7., 8., 8., 2., 9., 5., 1., 7., 6., 6., 3.])

In [ ]:
a.reshape(6,2)  # returns the array with a modified shape

array([[1., 7.],
       [8., 8.],
       [2., 9.],
       [5., 1.],
       [7., 6.],
       [6., 3.]])

In [ ]:
a.reshape(6,-1) # el -1 rellena todos los elementos.

array([[1., 7.],
       [8., 8.],
       [2., 9.],
       [5., 1.],
       [7., 6.],
       [6., 3.]])

In [ ]:
a.T

array([[1., 2., 7.],
       [7., 9., 6.],
       [8., 5., 6.],
       [8., 1., 3.]])

In [ ]:
a.T.shape

(4, 3)

- El orden de los elementos en la matriz resultante de `ravel()` es normalmente "estilo `C`", es decir, el índice de la derecha "cambia más rápido", por lo que el elemento después de un `[0,0]` es un `[0,1]`. 

- Si la matriz se reforma a otra forma, nuevamente la matriz se trata como "estilo `C`". NumPy normalmente crea matrices almacenadas en este orden, por lo que `ravel()` generalmente no necesitará copiar su argumento, pero si la matriz se hizo tomando segmentos de otra matriz o se creó con opciones inusuales, es posible que deba copiarse. 

- Las funciones `ravel()` y `reshape()` también se pueden instruir, utilizando un argumento opcional, para usar matrices de estilo FORTRAN, en las que el índice más a la izquierda cambia más rápido.

La función de `reshape` devuelve su argumento con una forma modificada, mientras que el método `ndarray.resize` modifica la matriz en sí:

In [ ]:
a

array([[1., 7., 8., 8.],
       [2., 9., 5., 1.],
       [7., 6., 6., 3.]])

In [ ]:
a.resize((2, 6))
a

array([[1., 7., 8., 8., 2., 9.],
       [5., 1., 7., 6., 6., 3.]])

***
## Concatenación de arreglos
Se pueden apilar varios arreglos a lo largo de diferentes ejes:

In [ ]:
a = np.floor(10*np.random.random((2,2)))
a

array([[2., 6.],
       [4., 1.]])

In [ ]:
b = np.floor(10*np.random.random((2,2)))
b

array([[3., 2.],
       [7., 3.]])

In [ ]:
# np.vstack pide una tupla de ndarrays 
np.vstack((a,b))

array([[2., 6.],
       [4., 1.],
       [3., 2.],
       [7., 3.]])

In [ ]:
# np.hstack pide una tupla de ndarrays 
np.hstack((a,b))

array([[2., 6., 3., 2.],
       [4., 1., 7., 3.]])

In [ ]:
np.column_stack((a,b)) # Equivalente a np.hstack para arreglos 2D

array([[2., 6., 3., 2.],
       [4., 1., 7., 3.]])

In [ ]:
np.hstack((a,b)) 

array([[2., 6., 3., 2.],
       [4., 1., 7., 3.]])

- Cuando los arreglos son 1D, `np.column_stack()` y `np.hstack()` se comportan diferente

In [173]:
a = np.array([4.,2.])
b = np.array([3.,8.])

In [ ]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [174]:
np.hstack((a,b)) 

array([4., 2., 3., 8.])

- Podemos crear nuevas dimensiones en el arreglo con `np.newaxis` o con `None`

In [ ]:
a[:, np.newaxis]

array([[4.],
       [2.]])

In [ ]:
a[:, None]

array([[4.],
       [2.]])

In [ ]:
a[np.newaxis,:]

array([[4., 2.]])

In [172]:
np.column_stack((a[:, np.newaxis], b[:, np.newaxis]))

array([[2. , 1.2],
       [3. , 3.5],
       [4. , 5.1]])

- Por otro lado, la función `row_stack` es equivalente a `vstack` para cualquier arreglo de entrada. De hecho, `row_stack` es un alias para `vstack`

In [ ]:
np.row_stack is np.vstack

- En general, para arreglos con más de dos dimensiones:
    
    - `hstack` apila a lo largo del segundo eje, 
    
    - `vstack` apila a lo largo del primer eje y 
    
    - `concatenate` permite argumentos opcionales que dan el número del eje (`axis`) a lo largo del cual debe ocurrir la concatenación.

***
## Separar un arreglo en varios más pequeños

In [ ]:
a = np.floor(10*np.random.random((2,12)))
a

array([[0., 5., 7., 2., 5., 1., 5., 2., 7., 8., 8., 3.],
       [0., 1., 6., 9., 3., 2., 8., 0., 7., 5., 0., 8.]])

In [ ]:
np.hsplit(a,3)   # Split a into 3

[array([[0., 5., 7., 2.],
        [0., 1., 6., 9.]]),
 array([[5., 1., 5., 2.],
        [3., 2., 8., 0.]]),
 array([[7., 8., 8., 3.],
        [7., 5., 0., 8.]])]

In [ ]:
np.hsplit(a, (3,4))   # Split a after the third and the fourth column

[array([[0., 5., 7.],
        [0., 1., 6.]]),
 array([[2.],
        [9.]]),
 array([[5., 1., 5., 2., 7., 8., 8., 3.],
        [3., 2., 8., 0., 7., 5., 0., 8.]])]

In [ ]:
help(np.hsplit)

***
# Mutabilidad y clonado

Al operar y manipular arreglos, los datos a veces se copian en un nuevo arreglo y otras no. Esto es a menudo una fuente de confusión para los principiantes. 

Hay tres casos:

In [ ]:
a = np.arange( 12 )
b = a
b is a

True

In [ ]:
b.shape = 3, 4
a.shape

(3, 4)

1. Cortar una matriz devuelve una vista de ella:

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
s = a[:, 1:3]
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
s is a

False

## Copia profunda 

El método de copy hace una copia completa de la matriz y sus datos.

In [ ]:
# a new array object with new data is created
d = a.copy()
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
d is a

False

In [ ]:
d == a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

***
# Rutinas de NumPy

[Rutinas y funcionalidad](https://numpy.org/devdocs/reference/routines.html#routines)

***
# Para usuarios ***pro*** (como ustedes)

## *Broadcasting* (difusión)

- Este mecanismo permite que las funciones universales manejen de manera significativa entradas que no tienen exactamente la misma forma.

[General Broadcasting Rules](https://numpy.org/devdocs/user/basics.broadcasting.html)

- Un ejemplo:

In [ ]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [ ]:
xx = x.reshape(4,1)
xx

array([[0],
       [1],
       [2],
       [3]])

In [ ]:
r = x + xx
r

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [ ]:
x.shape, xx.shape, r.shape

((4,), (4, 1), (4, 4))

- El *broadcasting* proporciona una forma conveniente de tomar el producto externo (o cualquier otra operación externa) de dos matrices. El siguiente ejemplo muestra una operación de adición externa de dos matrices 1D:

In [ ]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

In [ ]:
a[:, None] + b

Aquí, `None` inserta un nuevo eje en `a`, haciéndolo un arreglo bidimensional de `4x1`. Al combinar este arreglo de `4x1` con `b`, que tiene forma `(3,)`, resulta un arreglo de `4x3`

### ¿Por qué funciona?

- Cuando se operan dos arreglos, NumPy compara sus formas (`shape`) elemento a elemento, empezando por la última dimensión y hacia arriba. 

- Dos dimensiones son compatibles cuando:
    
    - Son iguales, o
    
    - Una de ellas es 1
    
- Cuando alguna de las dos dimensiones es uno, **se utiliza la otra**. 

    - En otras palabras, las dimensiones con tamaño 1 son "estiradas" o "copiadas" para ajustarse a la otra.

***
## *Fancy indexing* y trucos de indexación

- NumPy ofrece más funciones de indexación que las secuencias regulares de Python. Además de la indexación por enteros y sectores, como vimos antes, las matrices se pueden indexar por matrices de enteros y matrices de booleanos.

In [ ]:
a = np.arange(11)**2
a

In [ ]:
i = np.array( [ 1,1,3,8,5 ] )
i

In [ ]:
a[i]   # the elements of a at the positions i

In [ ]:
j = np.array([[ 3, 4], [ 9, 7 ]])  # a bidimensional array of indices
j

In [ ]:
a[j] # the same shape as j

- También podemos dar índices para más de una dimensión. Las matrices de índices para cada dimensión deben tener la misma forma.

In [ ]:
a = np.arange(12).reshape(3,4)
a

In [ ]:
i = np.array([[0,1], [1,2]])
j = np.array([[2,1], [3,3]])

In [ ]:
i

In [ ]:
j

In [ ]:
a[i,j] # i and j must have equal shape

In [ ]:
a[i,2]

In [ ]:
a[:,j]

***
### Búsqueda del máximo

In [ ]:
data = np.sin(np.arange(20)).reshape(5,4)
data

In [ ]:
# index of the maxima for each series
ind = data.argmax(axis=0)
ind

***
###  Asignación múltiple con indexación

In [ ]:
a = np.arange(5)
a

In [ ]:
a[[1,3,4]] = 0
a

In [ ]:
# Se queda la última asignación
a = np.arange(5)
a[[0,0,2]] = [1,2,3]
a

***
### Indexado con arreglos booleanos

- Cuando indexamos arreglos con otros arreglos de índices (enteros), proporcionamos la lista de índices para elegir. Con los índices booleanos, el enfoque es diferente; **elegimos explícitamente qué elementos de la matriz queremos y cuáles no**.

La forma más natural en la que uno puede pensar para la indexación booleana es usar matrices booleanas que tengan la misma forma que la matriz original:

In [ ]:
a = np.arange(12).reshape(3,4)
a

In [ ]:
b = a > 4
b

In [ ]:
a[b]

- También se puede utilizar en asignaciones:

In [ ]:
a[b] = 0
a

***
# Álgebra lineal

In [ ]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

In [ ]:
a.transpose()

In [ ]:
np.linalg.inv(a)

In [ ]:
np.eye(2)

In [ ]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

j @ j

In [ ]:
y = np.array([[5.], [7.]])
y

In [ ]:
np.linalg.solve(a, y)

In [ ]:
# eigenvalores y eigenvectores
np.linalg.eig(a)

***
# Ejercicios propuestos

1. De las siguientes secciones, revisa las funciones de NumPy disponibles para darte una idea de lo que es posible hacer. 

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimate` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 

    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 

    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

ModuleNotFoundError: No module named 'nashpy'